# Site settings
title:         Strandlines
description:    
baseurl:        
url:            

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         StephenP
  url:          
  email:        

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - Jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post
  
#Collections
collections:
  category:
  output: true
  
  defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
